### ISSUE TITLE
Get IP List

### ISSUE THREAD

**Issue by jugendhacker** [benjojo/dnsfs#3]
How can i get the ip list needed for dnsfs?

**Comment by benjojo** [comment]
If you can't get a list. Then you shouldn't try and run this.

This software isn't supported or suppose to be actually run as anything
serious

**Comment by jugendhacker** [comment]
Why you won't help me?

**Comment by benjojo** [comment]
At best, you can look at the blog post https://blog.benjojo.co.uk/post/dns-filesystem-true-cloud-storage-dnsfs for a rough guide on how to produce a IP list.

I will not give out open resolver lists, they are weaponisable for DDoS.

**Comment by jugendhacker** [comment]
The Problem is that my Internet connection is very slow (<8kps) so it would take round about a week to complete the masscan. Any tips?
