### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jugendhacker** [benjojo/dnsfs#4]
I got this error while uploading a file:

871 chunks need to be uploaded...
panic: runtime error: index out of range

goroutine 13 [running]:
main.getDNSserverShard(0x12758192, 0x8, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/dnsfs/.GOPATH/src/github.com/benjojo/dnsfs/dnsfs/dns.go:245 +0x2c0
main.uploadChunk(0x12758192, 0x8, 0x1, 0x129c42d0, 0xf0)
        /home/pi/dnsfs/.GOPATH/src/github.com/benjojo/dnsfs/dnsfs/dns.go:119 +0x80
created by main.handleUpload
        /home/pi/dnsfs/.GOPATH/src/github.com/benjojo/dnsfs/dnsfs/http.go:54 +0x1a0
`

**Comment by benjojo** [comment]
How large is your IP list? Very low numbers could trigger this

**Comment by jugendhacker** [comment]
It's round about 3900 IPs so is this not enough?
